openapi: 3.1.2
info:
  title: Apple School Manager API
  description: API for managing Apple School Manager resources.
  version: 0.1.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api-school.apple.com/v1
    description: Apple School Manager v1 API server
security:
  - bearerAuth: []
tags:
  - name: orgDevices
    description: Organization devices
  - name: appleCareCoverage
    description: AppleCare coverage
  - name: mdmServers
    description: Management servers
paths:
  /mdmServers:
    $ref: paths/mdmServers.yaml
  /mdmServers/{id}/relationships/devices:
    $ref: paths/mdmServers_{id}_relationships_devices.yaml
  /orgDevices:
    $ref: paths/orgDevices.yaml
  /orgDevices/{id}:
    $ref: paths/orgDevices_{id}.yaml
  /orgDevices/{id}/appleCareCoverage:
    $ref: paths/orgDevices_{id}_appleCareCoverage.yaml
  /orgDevices/{id}/assignedServer:
    $ref: paths/orgDevices_{id}_assignedServer.yaml
  /orgDevices/{id}/relationships/assignedServer:
    $ref: paths/orgDevices_{id}_relationships_assignedServer.yaml
  /orgDeviceActivities:
    $ref: paths/orgDeviceActivities.yaml
  /orgDeviceActivities/{id}:
    $ref: paths/orgDeviceActivities_{id}.yaml
components:
  securitySchemes:
    bearerAuth:
      description: >
        The Apple School Manager API requires an access token produced by a custom OAuth 2.0 authentication flow.
        [Learn more](https://developer.apple.com/documentation/apple-school-and-business-manager-api/implementing-oauth-for-the-apple-school-and-business-manager-api)
      type: http
      scheme: bearer
